<?php

/**
 * Snapshot: Transformed result of class_with_constants
 * Auto-generated by TransformationSnapshotTest
 */

/**
 * Class with constants that can be inlined.
 *
 * Before: class constant references
 * After: literal values inlined
 */
class Config
{
}
class Auth
{
    public function validateToken($token)
    {
        $lifetime = 3600;
        $algorithm = "sha256";
        if ($token !== null) {
            return "valid";
        }
        return "invalid";
    }
}
$version = 2 + 1;
$baseUrl = "https://api.example.com";
$retries = 3 * 2;
$timeout = 30 / 2;
echo "API Version: " . $version;
echo "URL: " . $baseUrl;