<?php

/**
 * Snapshot: Transformed result of complex_math_expressions
 * Auto-generated by TransformationSnapshotTest
 */

$diameter = 20;
$circumference = 62.8318;
$area = 314.159;
$rectangleArea = 50;
$rectanglePerimeter = 30;
$sum = 12;
$product = 60;
$average = 4;
echo "Circle area: " . $area;
echo "Rectangle area: " . $rectangleArea;
echo "Sum: " . $sum;