<?php

/**
 * Snapshot: Transformed result of complex_math_expressions
 * Auto-generated by TransformationSnapshotTest
 */

$diameter = 10 * 2;
$circumference = 2 * 3.14159 * 10;
$area = 3.14159 * 10 * 10;
$rectangleArea = 5 * 10;
$rectanglePerimeter = 2 * (5 + 10);
$sum = 3 + 4 + 5;
$product = 3 * 4 * 5;
$average = (3 + 4 + 5) / 3;
echo "Circle area: " . $area;
echo "Rectangle area: " . $rectangleArea;
echo "Sum: " . $sum;