<?php

/**
 * Snapshot: Transformed result of complex_isset_pattern
 * Auto-generated by TransformationSnapshotTest
 */

/**
 * Complex isset pattern that can be simplified to null coalescing.
 *
 * Before: verbose isset checks with default values
 * After: concise ?? operator usage
 */
$username = "default_username";
$username = $_GET["username"] ?? $username ?? null;
$password = "default_password";
$password = $_GET["password"] ?? $password ?? null;
$role = "guest";
$role = $_GET["role"] ?? $role ?? null;
$theme = "light";
$theme = $_COOKIE["theme"] ?? $theme ?? null;
echo "User: " . $username;
echo "Role: " . $role;