<?php

/**
 * Snapshot: Transformed result of if_return_pattern
 * Auto-generated by TransformationSnapshotTest
 */

/**
 * If-return patterns that can be converted to ternary operators.
 *
 * Before: verbose if-else return statements
 * After: concise ternary expressions
 */
class UserValidator
{
    public function isAdult($age)
    {
        return $age >= 18 ? true : false;
    }
    public function getStatus($isActive)
    {
        return $isActive ? "active" : "inactive";
    }
    public function getRole($isAdmin)
    {
        return $isAdmin ? "administrator" : "user";
    }
    public function getMessage($hasErrors)
    {
        return $hasErrors ? "Please fix the errors" : "All good!";
    }
}
function checkPermission($level)
{
    if ($level > 5) {
        return "allowed";
    }
    return "denied";
}
function getLabel($count)
{
    if ($count == 1) {
        return "item";
    }
    return "items";
}