<?php

/**
 * Snapshot: Transformed result of mixed_complexity
 * Auto-generated by TransformationSnapshotTest
 */

/**
 * Mixed complexity example combining multiple patterns.
 *
 * Demonstrates:
 * - Constant inlining
 * - isset to coalesce
 * - Math pre-computation
 * - String concatenation
 * - If-return to ternary
 */
class Calculator
{
    const PI = 3.14159;
    const E = 2.71828;
    const PRECISION = 2;
    public function circleArea($radius): string
    {
        $area = self::PI * $radius * $radius;
        if ($area > 100) {
            return "large";
        }
        return "small";
    }
}
$defaultX = $_GET["x"] ?? $defaultX ?? null;
$defaultY = $_GET["y"] ?? $defaultY ?? null;
$finalX = $defaultX + 10;
$finalY = $defaultY + 20;
$totalMultiplier = 6;
$label = 'Point: ';
echo $label . "(" . $finalX . ", " . $finalY . ")";
echo "Multiplier: " . $totalMultiplier;