<?php

/**
 * Snapshot: Transformed result of string_concatenation
 * Auto-generated by TransformationSnapshotTest
 */

$fullName = 'John' . " " . 'Doe';
$greeting = 'Hello, ' . "World" . "!";
$separator = '--' . "-" . "-" . "-";
$url = 'https' . "://" . 'example' . "." . 'com';
$key = 'user_' . '12345' . '_data';
$message = 'This is ' . 'a very ' . 'long ' . 'message.';
echo $fullName;
echo $greeting;
echo $url;