<?php

/**
 * Snapshot: Transformed result of string_concatenation
 * Auto-generated by TransformationSnapshotTest
 */

declare (strict_types=1);
$fullName = 'John Doe';
$url = 'https://example.com';
$key = 'user_12345_data';
$message = 'This is a very long message.';
echo $fullName;
echo 'Hello, World!';
echo $url;